#!/usr/bin/env bash
# Shared functions for VADE environment setup scripts.
# Sourced by bootstrap.sh (devcontainer) and cloud-setup.sh (web).

log() { echo "[vade-setup] $*"; }

check_cmd() {
  command -v "$1" >/dev/null 2>&1
}

ensure_dirs() {
  mkdir -p "$HOME/.vade/library/canvases" \
           "$HOME/.vade/library/entities" 2>/dev/null || \
    log "Warning: could not create $HOME/.vade subdirs. Check permissions."
}

ensure_tsx() {
  if check_cmd tsx; then
    log "tsx already installed: $(tsx --version 2>&1 | head -1)"
    return 0
  fi
  log "Installing tsx globally..."
  npm install -g tsx@4.21.0 --no-audit --no-fund
}

install_deps() {
  local dir="${1:-.}"
  if [ -f "$dir/package.json" ]; then
    log "Installing npm dependencies in $dir..."
    (cd "$dir" && npm install --no-audit --no-fund)
  fi
}

# Install the SessionStart hook that prints the discussions digest on
# every Claude Code session start. Idempotent. Safe no-op if the
# installer script is not present.
ensure_agent_hooks() {
  local script_dir="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/..}"
  if [ -f "$script_dir/install-agent-hooks.sh" ]; then
    bash "$script_dir/install-agent-hooks.sh" || \
      log "Warning: agent hook install failed; continuing."
  fi
}

print_versions() {
  local tsx_version claude_version

  if check_cmd tsx; then
    tsx_version="$(tsx --version 2>/dev/null | head -1)"
  else
    tsx_version="$(npx tsx --version 2>/dev/null | head -1 || true)"
    [ -n "$tsx_version" ] || tsx_version="not found"
  fi

  if check_cmd claude; then
    claude_version="$(claude --version 2>/dev/null || true)"
    if [ -n "$claude_version" ]; then
      claude_version="$claude_version (run: claude login if needed)"
    else
      claude_version="available (run: claude login)"
    fi
  else
    claude_version="not available"
  fi

  log "Tool versions:"
  log "  node: $(node --version 2>/dev/null || echo 'not found')"
  log "  npm:  $(npm --version 2>/dev/null || echo 'not found')"
  log "  git:  $(git --version 2>/dev/null || echo 'not found')"
  log "  tsx:  $tsx_version"
  log "  claude: $claude_version"
}

# ===== COO identity bootstrap helpers =====
# Used by scripts/coo-bootstrap.sh when OP_SERVICE_ACCOUNT_TOKEN is set.
# Fetch COO identity material from a 1Password vault named "COO" via the
# op CLI. Vault/item contract and the cloud-env boot flow are documented
# in vade-coo-memory/coo/cloud-env-bootstrap.md.

OP_VERSION_DEFAULT="2.31.0"
COO_AUTH_FP_EXPECTED="SHA256:9vxJc6c69L8eaR6CvwdZoYDco24W6yN6GkKwnsm8Uys"
COO_SIGN_FP_EXPECTED="SHA256:pZeA8xycAtIsVGwhMzR3mg4KG05n9ksFuy4F1ZVXn3A"

ensure_op_cli() {
  if check_cmd op; then
    log "op CLI present: $(op --version 2>&1 | head -1)"
    return 0
  fi

  local version="${OP_VERSION:-$OP_VERSION_DEFAULT}"
  local arch
  arch="$(uname -m)"
  case "$arch" in
    x86_64|amd64) arch=amd64 ;;
    aarch64|arm64) arch=arm64 ;;
    *) log "op CLI: unsupported arch '$arch'"; return 1 ;;
  esac

  local bindir="${HOME}/.local/bin"
  mkdir -p "$bindir"

  local url="https://cache.agilebits.com/dist/1P/op2/pkg/v${version}/op_linux_${arch}_v${version}.zip"
  local tmp
  tmp="$(mktemp -d)"
  log "Downloading op CLI v${version} (${arch})"
  if ! curl -sfL "$url" -o "$tmp/op.zip"; then
    log "op CLI download failed: $url"
    rm -rf "$tmp"
    return 1
  fi

  if check_cmd unzip; then
    unzip -qo "$tmp/op.zip" -d "$tmp"
  elif check_cmd python3; then
    python3 -m zipfile -e "$tmp/op.zip" "$tmp"
  else
    log "op CLI extraction failed: need 'unzip' or 'python3'."
    rm -rf "$tmp"
    return 1
  fi

  install -m 0755 "$tmp/op" "$bindir/op"
  rm -rf "$tmp"

  case ":$PATH:" in
    *":$bindir:"*) ;;
    *) export PATH="$bindir:$PATH" ;;
  esac

  if ! op --version >/dev/null 2>&1; then
    log "op CLI install appears broken"
    return 1
  fi
  log "Installed op CLI: $(op --version 2>&1 | head -1)"
}

# Pull PAT and AgentMail key from 1Password; write to ~/.vade/coo-env
# (0600) and into ~/.claude/settings.json env block so Claude Code
# resolves ${GITHUB_MCP_PAT} / ${AGENTMAIL_API_KEY} at startup.
fetch_coo_secrets() {
  local github_pat agentmail_key
  if ! github_pat="$(op read 'op://COO/vade-coo-self-2026-04/credential' 2>/dev/null)"; then
    log "Failed to read op://COO/vade-coo-self-2026-04/credential"
    return 1
  fi
  if ! agentmail_key="$(op read 'op://COO/agentmail-vade-coo/credential' 2>/dev/null)"; then
    log "Failed to read op://COO/agentmail-vade-coo/credential"
    return 1
  fi

  local env_file="${HOME}/.vade/coo-env"
  mkdir -p "$(dirname "$env_file")"
  (
    umask 077
    cat > "$env_file" <<EOF
# Auto-generated by coo-bootstrap.sh. Do not commit. chmod 600.
export GITHUB_MCP_PAT='$github_pat'
export GITHUB_TOKEN='$github_pat'
export AGENTMAIL_API_KEY='$agentmail_key'
EOF
  )
  chmod 600 "$env_file"

  _write_claude_settings_env "$github_pat" "$agentmail_key"

  export GITHUB_MCP_PAT="$github_pat"
  export GITHUB_TOKEN="$github_pat"
  export AGENTMAIL_API_KEY="$agentmail_key"
  log "Wrote $env_file and updated ~/.claude/settings.json env block"
}

# Merge COO env vars into ~/.claude/settings.json "env" object. Claude
# Code reads this at process startup, so ${GITHUB_MCP_PAT} etc. in
# .mcp.json substitute correctly. Idempotent.
_write_claude_settings_env() {
  local pat="$1" agentmail="$2"
  if ! check_cmd node; then
    log "Warning: node missing; skipping ~/.claude/settings.json env merge"
    return 0
  fi
  local settings_dir="${HOME}/.claude"
  local settings_file="$settings_dir/settings.json"
  mkdir -p "$settings_dir"
  [ -f "$settings_file" ] || echo '{}' > "$settings_file"

  GITHUB_MCP_PAT="$pat" AGENTMAIL_API_KEY="$agentmail" node -e '
    const fs = require("fs");
    const path = process.argv[1];
    let cfg = {};
    try { cfg = JSON.parse(fs.readFileSync(path, "utf8")) || {}; }
    catch (e) {
      console.error("[vade-setup] " + path + " unparseable; aborting env merge.");
      process.exit(1);
    }
    cfg.env = Object.assign({}, cfg.env || {}, {
      GITHUB_MCP_PAT: process.env.GITHUB_MCP_PAT,
      GITHUB_TOKEN: process.env.GITHUB_MCP_PAT,
      AGENTMAIL_API_KEY: process.env.AGENTMAIL_API_KEY,
    });
    fs.writeFileSync(path, JSON.stringify(cfg, null, 2) + "\n");
  ' "$settings_file"
  chmod 600 "$settings_file"
}

# Install COO SSH keys from 1Password into ~/.ssh/. Validates
# fingerprints against expected values; aborts on mismatch.
install_coo_ssh_keys() {
  local ssh_dir="${HOME}/.ssh"
  mkdir -p "$ssh_dir"
  chmod 700 "$ssh_dir"

  _op_to_file "op://COO/vade-coo-auth/private key" "$ssh_dir/vade-coo-auth"     0600 || return 1
  _op_to_file "op://COO/vade-coo-auth/public key"  "$ssh_dir/vade-coo-auth.pub" 0644 || return 1
  _op_to_file "op://COO/vade-coo-sign/private key" "$ssh_dir/vade-coo-sign"     0600 || return 1
  _op_to_file "op://COO/vade-coo-sign/public key"  "$ssh_dir/vade-coo-sign.pub" 0644 || return 1

  local fp_auth fp_sign
  fp_auth="$(ssh-keygen -lf "$ssh_dir/vade-coo-auth.pub" 2>/dev/null | awk '{print $2}')"
  fp_sign="$(ssh-keygen -lf "$ssh_dir/vade-coo-sign.pub" 2>/dev/null | awk '{print $2}')"
  if [ "$fp_auth" != "$COO_AUTH_FP_EXPECTED" ]; then
    log "FATAL: auth key fingerprint mismatch (got $fp_auth, expected $COO_AUTH_FP_EXPECTED)"
    return 1
  fi
  if [ "$fp_sign" != "$COO_SIGN_FP_EXPECTED" ]; then
    log "FATAL: signing key fingerprint mismatch (got $fp_sign, expected $COO_SIGN_FP_EXPECTED)"
    return 1
  fi

  local allowed="$ssh_dir/allowed_signers"
  {
    echo "coo@vade-app.dev $(cat "$ssh_dir/vade-coo-auth.pub")"
    echo "coo@vade-app.dev $(cat "$ssh_dir/vade-coo-sign.pub")"
  } > "$allowed"
  chmod 644 "$allowed"

  if ! grep -q '^github.com ' "$ssh_dir/known_hosts" 2>/dev/null; then
    ssh-keyscan -t rsa,ecdsa,ed25519 github.com 2>/dev/null >> "$ssh_dir/known_hosts" || true
    [ -f "$ssh_dir/known_hosts" ] && chmod 644 "$ssh_dir/known_hosts"
  fi
}

_op_to_file() {
  local ref="$1" path="$2" mode="$3"
  local content
  if ! content="$(op read "$ref" 2>/dev/null)"; then
    log "Failed to read $ref"
    return 1
  fi
  (
    umask 077
    printf '%s\n' "$content" > "$path"
  )
  chmod "$mode" "$path"
}

# Write ~/.gitconfig with COO identity + SSH signing + auth-key push.
# Per MEMO 2026-04-22-03, cloud sessions share the Mac's commit discipline.
write_coo_gitconfig() {
  local gc="${HOME}/.gitconfig"
  git config --file "$gc" user.name "COO"
  git config --file "$gc" user.email "coo@vade-app.dev"
  git config --file "$gc" gpg.format ssh
  git config --file "$gc" user.signingkey "${HOME}/.ssh/vade-coo-sign.pub"
  git config --file "$gc" commit.gpgsign true
  git config --file "$gc" tag.gpgsign true
  git config --file "$gc" gpg.ssh.allowedSignersFile "${HOME}/.ssh/allowed_signers"
  git config --file "$gc" core.sshCommand "ssh -i ${HOME}/.ssh/vade-coo-auth -o IdentitiesOnly=yes -o UserKnownHostsFile=${HOME}/.ssh/known_hosts"
  log "Configured $gc (user=COO, signing=ssh via vade-coo-sign.pub)"
}

validate_coo_identity() {
  local login
  login="$(curl -sfH "Authorization: Bearer ${GITHUB_MCP_PAT}" https://api.github.com/user \
    | grep -o '"login":"[^"]*"' \
    | head -1 \
    | cut -d'"' -f4)"
  if [ "$login" != "vade-coo" ]; then
    log "FATAL: GitHub PAT validates as '${login:-unknown}', expected 'vade-coo'"
    return 1
  fi
  log "GitHub PAT valid for: $login"
}

summarize_coo_identity() {
  local fp_auth fp_sign
  fp_auth="$(ssh-keygen -lf "${HOME}/.ssh/vade-coo-auth.pub" 2>/dev/null | awk '{print $2}')"
  fp_sign="$(ssh-keygen -lf "${HOME}/.ssh/vade-coo-sign.pub" 2>/dev/null | awk '{print $2}')"
  log "COO identity active"
  log "  auth  ${fp_auth:-unknown}"
  log "  sign  ${fp_sign:-unknown}"
  log "  agentmail key: $([ -n "${AGENTMAIL_API_KEY:-}" ] && echo present || echo MISSING)"
}
