#!/usr/bin/env bash
# UserPromptSubmit hook: drop self-echo <github-webhook-activity> blocks.
#
# The harness github MCP delivers every PR/issue event to every subscriber
# of mcp__github__subscribe_pr_activity, including the subscriber's own
# posts. Each self-echo costs ~600–1500 inbound tokens for zero signal
# value: the agent already knows what it just posted.
#
# This hook reads the UserPromptSubmit JSON on stdin, parses out the
# embedded user prompt, and decides whether the prompt is a pure
# self-echo. If so, it emits a `decision: "block"` JSON object on stdout
# (Claude Code erases the prompt from context and shows `reason` to the
# harness UI only). Otherwise it exits 0 with no output and the prompt
# passes through unchanged.
#
# Detection rule (all three required):
#   1. prompt contains at least one <github-webhook-activity>...</...> block;
#   2. no untagged content exists outside those blocks (mixed prompts
#      pass through);
#   3. every block embeds this session's session-URL trail
#      (`claude.ai/code/session_<sid_without_cse_prefix>` per
#      MEMO-2026-04-26-02 / coo-session-url.sh).
#
# Foreign-session sibling events (different session_id, no URL match)
# pass through unchanged. Same-session-fork echoes (deliberate
# claude --resume, or involuntary fork from usage-limit transport) DO
# match because forks share the session URL trail; that is the desired
# default behavior (their content was generated by a sibling fork that
# shares this session's identity).
#
# Opt-out: VADE_NO_SELF_ECHO_FILTER=1 disables the hook for the session.
# Useful when the loop itself is the experiment subject (briefing-005).
#
# Always exits 0 (fail-open). Any parsing error / missing field → no
# decision emitted → prompt passes through.
#
# vade-app/vade-runtime#136.

set -uo pipefail

[ "${VADE_NO_SELF_ECHO_FILTER:-0}" = "1" ] && exit 0

input="$(cat 2>/dev/null || true)"
[ -z "$input" ] && exit 0

session_id="$(printf '%s' "$input" | jq -r '.session_id // ""' 2>/dev/null || true)"
prompt="$(printf '%s' "$input" | jq -r '.prompt // ""' 2>/dev/null || true)"

[ -z "$session_id" ] && exit 0
[ -z "$prompt" ] && exit 0

# Cheap reject: no webhook block at all.
case "$prompt" in
  *"<github-webhook-activity>"*) ;;
  *) exit 0 ;;
esac

# Python parser — handles the regex, residue check, and per-block URL
# match cleanly. Stdin carries the prompt; SESSION_ID env carries the id.
verdict="$(SESSION_ID="$session_id" python3 -c '
import os, sys, re
sid = os.environ["SESSION_ID"]
sid = sid[4:] if sid.startswith("cse_") else sid
needle = "claude.ai/code/session_" + sid

prompt = sys.stdin.read()
pattern = re.compile(r"<github-webhook-activity>.*?</github-webhook-activity>", re.DOTALL)
blocks = pattern.findall(prompt)
if not blocks:
    print("PASS"); sys.exit(0)

residue = pattern.sub("", prompt).strip()
if residue:
    print("PASS"); sys.exit(0)

if not all(needle in b for b in blocks):
    print("PASS"); sys.exit(0)

print("BLOCK")
' <<<"$prompt" 2>/dev/null || echo PASS)"

if [ "$verdict" = "BLOCK" ]; then
  jq -n --arg sid "$session_id" '{
    decision: "block",
    reason: ("self-echo filter (vade-runtime#136): " + ($sid | tostring) + " — webhook block(s) embed this session'\''s URL trail; suppressed to dampen amplification.")
  }'
fi
exit 0
